library("ggplot2")
library("scales")
library("grid")
library("gridExtra")
args <- commandArgs()
mydata=read.csv(args[5],sep=" ")
theme_set(theme_bw())
 theme_update(plot.margin = unit(c(0,0,0,0), "cm"))
 mv=max(mydata$throughput)*1.4
p1=ggplot(data=mydata, aes(x=experiment, y=throughput, fill=structure)) + facet_grid(.~machine) +xlab("")+ylab("Throughput (Mops/s)") +geom_bar(stat="identity", colour="black",position=position_dodge())+geom_text(angle = 90, aes(label = paste(sprintf("%.1f", scalability), "", sep=""), y =throughput+mv/10), size = 5, position = position_dodge(width=0.9)) +scale_fill_brewer(palette="OrRd") + scale_x_discrete(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0),limits= c(0,mv))
mydata2=read.csv(args[6],sep=" ")
#print(p1 + scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)))
p2 = ggplot(data=mydata2, aes(y=throughput, x=cores, shape=structure, group=structure, colour=structure)) + geom_line(size=0.5) + geom_point(dat=mydata2[(mydata2$cores+c(mydata2$structure))%%10==0,],size=3, fill="white") +  facet_grid(.~machine,scales="free")+xlab("# threads") + ylab("Throughput (Mops/s)") +scale_fill_brewer(palette="OrRd") + scale_x_continuous(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0))+scale_shape_manual(values= c(0,1,2,3,4,5,15,16,17,18)) 
pdf(file=args[7],height=5.08,width=16.51)
grid.arrange(p2, p1)
dev.off()
