default: all


all:
	gnuplot gp/ot.gp	
	gnuplot gp/map.gp	
	gnuplot gp/ll.gp
	gnuplot gp/ll_small.gp
	gnuplot gp/ht.gp
	gnuplot gp/ht_small.gp
	gnuplot gp/sl.gp	
	gnuplot gp/sl_small.gp
	gnuplot gp/qu.gp	
	gnuplot gp/st.gp	
	gnuplot gp/st_small.gp	

fixed:
	gnuplot gp/ot_fixed.gp	
	gnuplot gp/map_fixed.gp	
	gnuplot gp/ll_fixed2.gp
	gnuplot gp/ht_fixed2.gp
	gnuplot gp/ht_fixed_all2.gp
	gnuplot gp/sl_fixed2.gp
	gnuplot gp/qu_fixed.gp	
	gnuplot gp/st_fixed.gp	

camera:
	gnuplot gp/map.gp	
	gnuplot gp/ll2.gp
	gnuplot gp/ht2.gp
	gnuplot gp/ht_small2.gp
	gnuplot gp/sl2.gp
	gnuplot gp/sl_small2.gp
