default: all


all:
	gnuplot gp/ot.gp	
	gnuplot gp/map.gp	
	gnuplot gp/ll.gp
	gnuplot gp/ll_small.gp
	gnuplot gp/ht.gp
	gnuplot gp/ht_small.gp
	gnuplot gp/sl.gp	
	gnuplot gp/sl_small.gp
	gnuplot gp/qu.gp	
	gnuplot gp/st.gp	
	gnuplot gp/st_small.gp	

